Add Actions for rekernel

diff --git a/.github/workflows/compile-kernel.yml b/.github/workflows/compile-kernel.yml
--- a/.github/workflows/compile-kernel.yml
+++ b/.github/workflows/compile-kernel.yml
@@ -1,94 +1,59 @@
 #==========================================================================
-# Description: Compile the kernel
-# Copyright (C) 2021 https://github.com/unifreq/openwrt_packit
-# Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
-# Copyright (C) 2021 https://github.com/ophub/fnnas
+# Description: Compile the fnnas kernel
+# Copyright (C) 2025 https://fnnas.com
+# Copyright (C) 2026 https://github.com/ophub/fnnas
 #==========================================================================
 
-name: Compile the kernel
+name: Compile the fnnas kernel
 
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      kernel_source:
-        description: "Select the kernel source"
+      fnnas_repo:
+        description: "Set fnnas source repository"
         required: false
-        default: "unifreq"
+        default: "ophub/fnnas"
         type: choice
         options:
-          - unifreq
-          - ophub
-      kernel_version:
-        description: "Select kernel version"
+          - ophub/fnnas
+      fnnas_base_version:
+        description: "Select fnnas base image version"
+        required: false
+        default: "amlogic_300"
+        type: choice
+        options:
+          - amlogic_300
+          - rockchip_296
+      debs_version:
+        description: "Set fnnas debs version"
         required: false
         default: "6.12.y"
         type: choice
         options:
-          - 5.10.y
-          - 5.15.y
-          - 6.1.y
-          - 6.6.y
           - 6.12.y
-      kernel_auto:
-        description: "Auto use the latest kernel"
+      debs_install:
+        description: "Install kernel debs files"
+        required: false
+        default: "no"
+        type: choice
+        options:
+          - amlogic
+          - allwinner
+          - rockchip
+          - no
+      dtbs_install:
+        description: "Install kernel dtbs files"
         required: false
         default: true
         type: boolean
-      delete_source:
-        description: "Delete source after compilation"
-        required: false
-        default: true
-        type: boolean
-      kernel_package:
-        description: "Select compile package list"
-        required: false
-        default: "all"
-        type: choice
-        options:
-          - all
-          - dtbs
-      kernel_toolchain:
-        description: "Select the compilation toolchain"
-        required: false
-        default: "gcc"
-        type: choice
-        options:
-          - clang
-          - gcc
-          - gcc-15.2
-          - gcc-14.3
-          - gcc-14.2
-      ccache_clear:
-        description: "Set whether to clear the cache"
-        required: false
-        default: false
-        type: boolean
-      docker_image:
-        description: "Select Armbian docker image"
-        required: false
-        default: "trixie"
-        type: choice
-        options:
-          - trixie
-          - bookworm
-          - noble
-          - jammy
-      kernel_sign:
-        description: "Set the kernel custom signature"
-        required: false
-        default: "-ophub"
-        type: choice
-        options:
-          - -ophub
-          - -yourname
 
 env:
   TZ: Etc/UTC
 
 jobs:
   build:
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-24.04
     if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
 
     steps:
@@ -107,7 +72,7 @@ jobs:
           sudo rm -f /swapfile /mnt/swapfile
           sudo -E apt-get -y update
           sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
-          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-build-armbian-depends)
+          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-fnnas-depends)
           sudo -E systemctl daemon-reload
           #sudo -E apt-get -y full-upgrade
           sudo -E apt-get -y autoremove --purge
@@ -141,50 +106,68 @@ jobs:
           df -Th
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Get kernel source hash
-        id: kernelhash
+      - name: Download latest fnnas image
+        id: down
+        working-directory: /builder
+        if: (!cancelled())
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # Get the latest source hash from the kernel repository
-          api_url="https://api.github.com/repos/${{ inputs.kernel_source }}/linux-${{ inputs.kernel_version }}/git/ref/heads/main"
-          source_hash=$(curl -fsSL -m 20 \
+          echo "Starting to download the latest fnnas base image..."
+          fnnas_base_version="${{ inputs.fnnas_base_version }}"
+          [[ -d "fnnas" ]] || mkdir -p fnnas
+
+          latest_version=$(curl -s \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-              ${api_url} |
-              jq -r '.object.sha'
-          )
-          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
-          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
+              https://api.github.com/repos/ophub/fnnas/releases?per_page=20 | \
+              jq -r --arg RTK "fnnas_base_image" \
+              --arg BOARD "${fnnas_base_version}" \
+              '[.[] | select(.tag_name | contains($RTK))] |
+              map(.assets[] | select(.name | contains($BOARD) and endswith(".img.xz"))) |
+              sort_by(.updated_at) |
+              reverse |
+              .[0] |
+              {data: .updated_at, url: .url, name: .name}')
+
+          [[ -z "${latest_version}" || "${latest_version}" == "null" ]] && {
+              echo "Invalid fnnas image file download address."
+              exit 1
+          }
+
+          latest_url="$(echo ${latest_version} | jq -r '.url')"
+          fnnas_filename="$(echo ${latest_version} | jq -r '.name')"
+          echo "Downloading: ${fnnas_filename}"
+          echo "Source: ${latest_url}"
+
+          curl -fsSL \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/octet-stream" \
+              "${latest_url}" \
+              -o "fnnas/${fnnas_filename}"
+
+          [[ "${?}" -ne "0" ]] && echo "Download failed." && exit 1
+
+          ln -sf /builder/fnnas ${{ github.workspace }}/fnnas
+          ln -sf /builder/fnnas /home/runner/work/_actions/ophub/fnnas/main/fnnas
+
           echo "status=success" >> ${GITHUB_OUTPUT}
 
-      - name: Cache ccache
-        uses: actions/cache@v4
-        with:
-          path: /builder/ccache
-          key: kernel-${{ inputs.kernel_toolchain }}-${{ inputs.kernel_version }}-${{ env.source_hash }}
-          restore-keys: |
-            kernel-${{ inputs.kernel_toolchain }}-${{ inputs.kernel_version }}-
-
-      - name: Compile the kernel [ ${{ inputs.kernel_version }} ]
-        uses: ophub/amlogic-s9xxx-armbian@main
-        if: ${{ steps.disk.outputs.status }} == 'success' && !cancelled()
+      - name: Compile the fnnas kernel [ ${{ inputs.debs_version }} ]
+        uses: ophub/fnnas@main
+        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
         with:
           build_target: kernel
-          kernel_source: ${{ inputs.kernel_source }}
-          kernel_version: ${{ inputs.kernel_version }}
-          kernel_auto: ${{ inputs.kernel_auto }}
-          delete_source: ${{ inputs.delete_source }}
-          kernel_package: ${{ inputs.kernel_package }}
-          kernel_sign: ${{ inputs.kernel_sign }}
-          kernel_toolchain: ${{ inputs.kernel_toolchain }}
-          ccache_clear: ${{ inputs.ccache_clear }}
-          docker_hostpath: /builder
-          docker_image: ophub/armbian-${{ inputs.docker_image }}:arm64
+          fnnas_repo: ${{ inputs.fnnas_repo }}
+          debs_version: ${{ inputs.debs_version }}
+          debs_install: ${{ inputs.debs_install }}
+          debs_install: ${{ inputs.debs_install }}
 
       - name: Upload Kernel to Release
         uses: ncipollo/release-action@main
         if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
-          tag: kernel_stable
+          tag: kernel_fnnas
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           removeArtifacts: false
@@ -192,9 +175,9 @@ jobs:
           makeLatest: false
           token: ${{ secrets.GITHUB_TOKEN }}
           body: |
-            - These are Mainline LTS(Long Term Support) kernels that provide `stable` support for FnNAS.
-            - It works with most `Amlogic`, `Rockchip`, and `Allwinner` devices. For specific details, please refer to the instructions on the homepage of repository.
-            - Dedicated BSP kernels for other Rockchip and Allwinner devices can be downloaded from the [ophub/kernel](https://github.com/ophub/kernel) repository.
-            - 这些是主线 LTS（长期支持）内核，为 FnNAS 提供`稳定`的支持。
-            - 适用于 `amlogic`，`rockchip`，`allwinner` 的大部分设备，具体可以参考仓库首页的说明。
-            - 其他的 Rockchip 和 Allwinner 设备专用 BSP 内核可以在 [ophub/kernel](https://github.com/ophub/kernel) 仓库里下载使用。
+            - FnNAS Dedicated Kernel. Based on official [dtbs](https://github.com/ophub/fnnas/releases/tag/kernel_fnnas) packages from `fnnas.com`,
+              and repackaged into .tar.gz format using the `rekernel` tool.
+              It is optimized for batch packaging and supports online updates via the `fnnas-update` command.
+            - FnNAS 专用内核。基于 `fnnas.com` 官方提供的 [dtbs](https://github.com/ophub/fnnas/releases/tag/kernel_fnnas) 安装包，
+              利用本仓库的 `rekernel` 工具重新封装为 .tar.gz 格式。
+              该内核既适用于批量打包，也支持通过 `fnnas-update` 命令进行在线更新。
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -2,10 +2,12 @@ name: "Make Fnnas"
 author: "https://github.com/ophub/fnnas"
 description: "Support Amlogic, Rockchip and Allwinner boxes."
 inputs:
-  mode:
-    description: "Select script."
+  # Select build target
+  build_target:
+    description: "Select build target: fnnas / kernel"
     required: false
-    default: "ophub"
+    default: "fnnas"
+  # For build fnnas -----
   fnnas_path:
     description: "Set fnnas arm64 file path."
     required: false
@@ -34,6 +36,23 @@ inputs:
     description: "Set fnnas builder signature."
     required: false
     default: ""
+  # For compile kernel -----
+  fnnas_repo:
+    description: "Set fnnas source repository."
+    required: false
+    default: "ophub/fnnas"
+  debs_version:
+    description: "Set fnnas debs version."
+    required: false
+    default: "6.12.y"
+  debs_install:
+    description: "Install kernel debs for specified platform"
+    required: false
+    default: "no"
+  dtbs_install:
+    description: "Install kernel dtbs for specified platform"
+    required: false
+    default: "no"
 
 runs:
   using: "composite"
@@ -42,70 +61,105 @@ runs:
       run: |
         cd ${{ github.action_path }}
         echo -e "ophub package actions path: [ ${PWD} ]"
+        build_target="${{ inputs.build_target }}"
+        [[ -z "${build_target}" ]] && build_target="fnnas"
 
-        fnnas_filename="${{ inputs.fnnas_path }}"
-        fnnas_savefile="${fnnas_filename##*/}"
-        fnnas_savepath="fnnas-arm64"
-        fnnas_outpath="fnnas/out"
-        echo -e "Get fnnas file input parameters: [ ${fnnas_filename} ]"
-        [[ -z "${fnnas_filename}" ]] && echo -e "The [ fnnas_path ] variable must be specified." && exit 1
-        [[ -d "${fnnas_savepath}" ]] || mkdir -p ${fnnas_savepath}
-        [[ -d "${fnnas_outpath}" ]] || mkdir -p ${fnnas_outpath}
+        if [[ "${build_target}" == "fnnas" ]]; then
+            echo -e "Start rebuilding fnnas..."
 
-        if [[ "${fnnas_filename}" =~ ^http ]]; then
-            echo -e "Download file: [ ${fnnas_filename} ]"
-            curl -fsSL "${fnnas_filename}" -o "${fnnas_savepath}/${fnnas_savefile}"
-        else
-            if [[ -z "$(ls ${fnnas_savepath}/${fnnas_savefile} 2>/dev/null)" ]]; then
-                echo -e "Copy fnnas rootfs file: [ ${fnnas_filename} ]"
-                if [[ "${fnnas_filename}" =~ ^/ ]]; then
-                    cp -vf ${fnnas_filename} ${fnnas_savepath}/ || true
-                else
-                    cp -vf ${{ github.workspace }}/${fnnas_filename} ${fnnas_savepath}/ || true
-                fi
+            fnnas_filename="${{ inputs.fnnas_path }}"
+            fnnas_savefile="${fnnas_filename##*/}"
+            fnnas_savepath="fnnas-arm64"
+            fnnas_outpath="fnnas/out"
+            echo -e "Get fnnas file input parameters: [ ${fnnas_filename} ]"
+            [[ -z "${fnnas_filename}" ]] && echo -e "The [ fnnas_path ] variable must be specified." && exit 1
+            [[ -d "${fnnas_savepath}" ]] || mkdir -p ${fnnas_savepath}
+            [[ -d "${fnnas_outpath}" ]] || mkdir -p ${fnnas_outpath}
+
+            if [[ "${fnnas_filename}" =~ ^http ]]; then
+                echo -e "Download file: [ ${fnnas_filename} ]"
+                curl -fsSL "${fnnas_filename}" -o "${fnnas_savepath}/${fnnas_savefile}"
             else
-                echo -e "The [ ${fnnas_savepath}/${fnnas_savefile} ] file already exists, skipping."
+                if [[ -z "$(ls ${fnnas_savepath}/${fnnas_savefile} 2>/dev/null)" ]]; then
+                    echo -e "Copy fnnas rootfs file: [ ${fnnas_filename} ]"
+                    if [[ "${fnnas_filename}" =~ ^/ ]]; then
+                        cp -vf ${fnnas_filename} ${fnnas_savepath}/ || true
+                    else
+                        cp -vf ${{ github.workspace }}/${fnnas_filename} ${fnnas_savepath}/ || true
+                    fi
+                else
+                    echo -e "The [ ${fnnas_savepath}/${fnnas_savefile} ] file already exists, skipping."
+                fi
             fi
-        fi
-        sync
-        echo -e "About the [ ${fnnas_savepath} ] directory: \n$(ls -lh ${fnnas_savepath} 2>/dev/null)"
+            sync
+            echo -e "About the [ ${fnnas_savepath} ] directory: \n$(ls -lh ${fnnas_savepath} 2>/dev/null)"
 
-        cd ${fnnas_savepath}
-        echo -e "Check the fnnas file format..."
-        down_file="$(ls -l *.img* 2>/dev/null | grep "^-" | awk '{print $9}' | sort -u | head -n 1)"
-        if [[ -n "${down_file}" ]]; then
-            echo -e "Selected fnnas file: [ ${down_file} ]"
+            cd ${fnnas_savepath}
+            echo -e "Check the fnnas file format..."
+            down_file="$(ls -l *.img* 2>/dev/null | grep "^-" | awk '{print $9}' | sort -u | head -n 1)"
+            if [[ -n "${down_file}" ]]; then
+                echo -e "Selected fnnas file: [ ${down_file} ]"
+            else
+                echo -e "The fnnas file is invalid."
+                exit 1
+            fi
+            [[ "${down_file:0-7}" == ".img.gz" ]] && gzip -df ${down_file} 2>/dev/null && sync
+            [[ "${down_file:0-7}" == ".img.xz" ]] && xz -d ${down_file} 2>/dev/null && sync
+            [[ "${down_file:0-4}" == ".zip" ]] && unzip -o ${down_file} 2>/dev/null && sync
+            echo -e "fnnas file: \n$(ls -lh *.img 2>/dev/null)"
+
+            cd ${{ github.action_path }}
+            echo -e "Start to make fnnas..."
+            make_command=""
+            [[ -n "${{ inputs.fnnas_board }}" ]] && make_command="${make_command} -b ${{ inputs.fnnas_board }}"
+            [[ -n "${{ inputs.kernel_repo }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
+            [[ -n "${{ inputs.fnnas_kernel }}" ]] && make_command="${make_command} -k ${{ inputs.fnnas_kernel }}"
+            [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
+            [[ -n "${{ inputs.fnnas_size }}" ]] && make_command="${make_command} -s ${{ inputs.fnnas_size }}"
+            [[ -n "${{ inputs.builder_name }}" ]] && make_command="${make_command} -n ${{ inputs.builder_name }}"
+            read -r -a make_args <<< "${make_command}"
+            sudo ./renas "${make_args[@]}"
+
+            cd ${{ github.action_path }}
+            echo -e "Output environment variables."
+            echo "PACKAGED_OUTPUTPATH=${PWD}/${fnnas_outpath}" >> ${GITHUB_ENV}
+            echo "PACKAGED_OUTPUTDATE=$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
+            echo "PACKAGED_STATUS=success" >> ${GITHUB_ENV}
+            echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${fnnas_outpath}"
+            echo -e "PACKAGED_OUTPUTDATE: $(date +"%m.%d.%H%M")"
+            echo -e "PACKAGED_STATUS: success"
+            echo -e "PACKAGED_OUTPUTPATH files list: \n$(ls -lh ${PWD}/${fnnas_outpath}/ 2>/dev/null)"
+
+        elif [[ "${build_target}" == "kernel" ]]; then
+            echo -e "Start to make fnnas kernel..."
+
+            # Prepare output directory
+            kernel_outpath="fnnas/out"
+            [[ -d "${kernel_outpath}" ]] || mkdir -p ${kernel_outpath}
+
+            cd ${{ github.action_path }}
+            make_command=""
+            [[ -n "${{ inputs.debs_install }}" ]] && make_command="${make_command} -e ${{ inputs.debs_install }}"
+            [[ -n "${{ inputs.dtbs_install }}" ]] && make_command="${make_command} -t ${{ inputs.dtbs_install }}"
+            [[ -n "${{ inputs.fnnas_repo }}" ]] && make_command="${make_command} -r ${{ inputs.fnnas_repo }}"
+            [[ -n "${{ inputs.debs_version }}" ]] && make_command="${make_command} -k ${{ inputs.debs_version }}"
+            read -r -a make_args <<< "${make_command}"
+            sudo ./rekernel "${make_args[@]}"
+
+            cd ${{ github.action_path }}
+            echo -e "Output environment variables."
+            echo "PACKAGED_OUTPUTPATH=${PWD}/${kernel_outpath}" >> ${GITHUB_ENV}
+            echo "PACKAGED_OUTPUTDATE=$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
+            echo "PACKAGED_STATUS=success" >> ${GITHUB_ENV}
+            echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${kernel_outpath}"
+            echo -e "PACKAGED_OUTPUTDATE: $(date +"%m.%d.%H%M")"
+            echo -e "PACKAGED_STATUS: success"
+            echo -e "PACKAGED_OUTPUTPATH files list: \n$(ls -lh ${PWD}/${kernel_outpath}/ 2>/dev/null)"
+
         else
-            echo -e "The fnnas file is invalid."
+            echo -e "Please select a build target: fnnas / kernel"
             exit 1
         fi
-        [[ "${down_file:0-7}" == ".img.gz" ]] && gzip -df ${down_file} 2>/dev/null && sync
-        [[ "${down_file:0-7}" == ".img.xz" ]] && xz -d ${down_file} 2>/dev/null && sync
-        [[ "${down_file:0-4}" == ".zip" ]] && unzip -o ${down_file} 2>/dev/null && sync
-        echo -e "fnnas file: \n$(ls -lh *.img 2>/dev/null)"
-
-        cd ${{ github.action_path }}
-        echo -e "Start to make fnnas..."
-        make_command=""
-        [[ -n "${{ inputs.fnnas_board }}" ]] && make_command="${make_command} -b ${{ inputs.fnnas_board }}"
-        [[ -n "${{ inputs.kernel_repo }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
-        [[ -n "${{ inputs.fnnas_kernel }}" ]] && make_command="${make_command} -k ${{ inputs.fnnas_kernel }}"
-        [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
-        [[ -n "${{ inputs.fnnas_size }}" ]] && make_command="${make_command} -s ${{ inputs.fnnas_size }}"
-        [[ -n "${{ inputs.builder_name }}" ]] && make_command="${make_command} -n ${{ inputs.builder_name }}"
-        read -r -a make_args <<< "${make_command}"
-        sudo ./renas "${make_args[@]}"
-
-        cd ${{ github.action_path }}
-        echo -e "Output environment variables."
-        echo "PACKAGED_OUTPUTPATH=${PWD}/${fnnas_outpath}" >> ${GITHUB_ENV}
-        echo "PACKAGED_OUTPUTDATE=$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
-        echo "PACKAGED_STATUS=success" >> ${GITHUB_ENV}
-        echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${fnnas_outpath}"
-        echo -e "PACKAGED_OUTPUTDATE: $(date +"%m.%d.%H%M")"
-        echo -e "PACKAGED_STATUS: success"
-        echo -e "PACKAGED_OUTPUTPATH files list: \n$(ls -lh ${PWD}/${fnnas_outpath}/ 2>/dev/null)"
-
 branding:
   icon: "terminal"
   color: "gray-dark"
